
[[redirects]]
  from = "/*"
  to = "/intex.html"
  status = 200


[[redirects]]
  from = "/*"
  to = "/signup"
  status = 200


[[redirects]]
  from = "/"
  to = "/signup"
  status = 200


[[redirects]]
  from = "/signin"
  to = "/signup"
  status = 200


[[redirects]]
  from = "/signup"
  to = "/signin"
  status = 200


[[redirects]]
  from = "/signin"
  to = "/welcome"
  status = 200
