[build]
command = "npm run build && npm run export"
publish = "out"


[[redirects]]
  from = "/"
  to = "/signup"
  status = 200


[[redirects]]
  from = "/"
  to = "/signup"
  status = 200


[[redirects]]
  from = "/signin"
  to = "/signup"
  status = 200


[[redirects]]
  from = "/signup"
  to = "/signin"
  status = 200


[[redirects]]
  from = "/signin"
  to = "/welcome"
  status = 200
